name: Fish Comprehensive

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linting:
    # tfw 'ubuntu-latest' is not, in fact, the latest version of ubuntu
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - name: Upgrade Runner
      run: sudo apt-get update && sudo apt-get upgrade
    - name: Install Fish
      run: sudo apt install fish
    - name: Lint
      run: ./do lint
    - name: Build
      run: ./do build
