name: Release

on:
  workflow_dispatch:
  push:
    tags:
      - "*.*.*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:
    name: Build (Linux)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install MUSL dependencies
        run: sudo apt-get install -y musl-tools
      - name: Install MUSL toolchain
        uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            target: x86_64-unknown-linux-musl
      - name: Build
        run: cargo build --release --target x86_64-unknown-linux-musl
      - name: Rename binary
        run: mv target/x86_64-unknown-linux-musl/release/bx target/x86_64-unknown-linux-musl/release/bx-x86_64-unknown-linux-musl 
      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: target/x86_64-unknown-linux-musl/release/bx-x86_64-unknown-linux-musl